[package]
name = "xdg-desktop-portal-gtk4"
version = "1.5.1"
edition = "2024"
rust-version = "1.92"
publish = false

[package.metadata.i18n]
available-locales = [
  "en",
  "be",
  "ca",
  "cs",
  "da",
  "de",
  "es",
  "fr",
  "gl",
  "he",
  "hi",
  "hr",
  "hu",
  "id",
  "ie",
  "it",
  "ja",
  "ka",
  "lt",
  "nl",
  "oc",
  "pl",
  "pt",
  "ru",
  "sk",
  "sl",
  "sr",
  "sv",
  "tr",
  "uk",
  "zh",
]
default-locale = "en"
load-path = "locales"

[dependencies]
current_locale = "0.1"
fastrand = { version = "2", optional = true }
futures-util = "0.3"
gdk-pixbuf = { version = "0.22", optional = true }
gdk4-wayland = "0.11"
gdk4-x11 = { version = "0.11" }
gtk4 = "0.11"
language-tags = "0.3"
notify = "8"
parking_lot = "0.12"
rust-i18n = "4"
rustix = { version = "1", features = ["pipe", "process"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt", "sync"] }
tracing = "0.1"
tracing-journald = { version = "0.3", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zbus = { version = "5", default-features = false, features = ["tokio"] }

[dev-dependencies]
tokio = { version = "1", features = ["time"] }

[features]
default = [
  "access",
  "account",
  "app_chooser",
  "clipboard",
  "dynamic_launcher",
  "email",
  "file_chooser",
  "inhibit",
  "lockdown",
  "notification",
  "print",
  "settings",
  "systemd",
  "usb",
]

access = []
account = []
app_chooser = []
clipboard = []
dynamic_launcher = []
email = []
file_chooser = []
inhibit = []
lockdown = []
notification = ["dep:gdk-pixbuf"]
print = ["dep:fastrand"]
settings = []
systemd = ["dep:tracing-journald"]
usb = []

[lints.clippy]
# Enforces flattening nested blocks into let-else
manual_let_else = "deny"

# Activates the custom ban lists defined in clippy.toml
disallowed_methods = "deny"
disallowed_types = "deny"

[profile.release]
opt-level = 3
strip = true
lto = "fat"
panic = "abort"
codegen-units = 1
