[package]
name = "xdg-desktop-portal-gtk4"
version = "1.5.1"
edition = "2024"
rust-version = "1.92"
publish = false

[package.metadata.i18n]
available-locales = [
  "en",
  "be",
  "ca",
  "cs",
  "da",
  "de",
  "es",
  "fr",
  "gl",
  "he",
  "hi",
  "hr",
  "hu",
  "id",
  "ie",
  "it",
  "ja",
  "ka",
  "lt",
  "nl",
  "oc",
  "pl",
  "pt",
  "ru",
  "sk",
  "sl",
  "sr",
  "sv",
  "tr",
  "uk",
  "zh",
]
default-locale = "en"
load-path = "locales"

[dependencies]
current_locale = "0.1.1"
fastrand = { version = "2.3", optional = true }
futures-util = "0.3.32"
gdk-pixbuf = { version = "0.22.0", optional = true }
gdk4-wayland = "0.11.4"
gdk4-x11 = { version = "0.11.4" }
gtk4 = "0.11.4"
language-tags = "0.3.2"
notify = "8.2.0"
parking_lot = "0.12.5"
rust-i18n = "4.2.0"
rustix = { version = "1.1", features = ["pipe", "process"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
tokio = { version = "1", features = ["macros", "rt", "sync"] }
tracing = "0.1.44"
tracing-journald = { version = "0.3.2", optional = true }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
zbus = { version = "5.17.0", default-features = false, features = ["tokio"] }

[dev-dependencies]
tokio = { version = "1", features = ["time"] }

[features]
default = [
  "access",
  "account",
  "app_chooser",
  "clipboard",
  "dynamic_launcher",
  "email",
  "file_chooser",
  "inhibit",
  "lockdown",
  "notification",
  "print",
  "settings",
  "systemd",
  "usb",
]

access = []
account = []
app_chooser = []
clipboard = []
dynamic_launcher = []
email = []
file_chooser = []
inhibit = []
lockdown = []
notification = ["dep:gdk-pixbuf"]
print = ["dep:fastrand"]
settings = []
systemd = ["dep:tracing-journald"]
usb = []

[profile.release]
opt-level = 3
strip = true
lto = "fat"
panic = "abort"
codegen-units = 1
