name: NixOS CI

on:
  pull_request:
    paths:
      - "**.rs"
      - "**Cargo.toml"
      - "**Cargo.lock"
      - "**.nix"
      - "flake.lock"
  push:
    paths:
      - "**.rs"
      - "**Cargo.toml"
      - "**Cargo.lock"
      - "**.nix"
      - "flake.lock"

permissions:
  contents: read

jobs:
  nix-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.2.2

      - name: Install and Setup Nix
        uses: DeterminateSystems/determinate-nix-action@61cbfe2efc2d4e7a8a6d56967c3c1058e846c858 # v3.21.9

      - name: Check Flake
        run: nix flake check

      - name: Build
        run: nix build

      - name: Build with DBus Tests
        run: nix build .#xdg-desktop-portal-gtk4-tests

      - name: Check formatting
        run: nix develop --command cargo fmt --check

      - name: Run clippy
        run: nix develop --command cargo clippy --all-targets --all-features -- -D warnings
